= Asciidoctor Book


This is a template repository for quick starting asciidoctor book. 

. Latex 
. BibTex support


== Setup 

Asciidoctor has tools in Java, Javascript, Ruby, and historically Python. At this time, much of the tools are in Ruby.  So we need to setup ruby environment properly.

.Install `rbenv` if not already found
[source,bash]
brew install rbenv # or conda install rbenv
rbenv init
rbenv install 2.7.4   # install this version 
rbenv global 2.7.4    # activate env


.Install asciidoctor and its extensions:
[source,bash]
----
gem install asciidoctor
gem install rouge
gem install asciidoctor-latex --pre      # this is for HTML
gem install asciidoctor-bibtex
gem install asciidoctor-indir_ext

gem install asciidoctor-pdf
# follow instructions on https://github.com/asciidoctor/asciidoctor-mathematical 
gem install asciidoctor-mathematical      # for latex in PDF
----

== Editor/IDE

* PyCharm with Asciidoctor extension
* VS Code with Asciidoctor extension


Both of them are great! I used to use PyCharm, but now I am considering VS Code, simply because https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/915#issue-1053008459[enabling extensions is easier than PyCharm's counterpart^].

1. Cmd Pallet >  `Asciidoc: Change preview security settings`  > Allow everything (i.e.`Disable`)

2. Settings > Asciidoc > 

.. Set "Full path for the asciidoctor binary/executable" as  `asciidoctor  -r asciidoctor-bibtex --trace`
.. Disable asciidoctor-js so our above command is used to render html in live preview


== Build

Just run 

   ./make.sh

